import Creator from "./models/Creator.js";
import mongoose from "mongoose";
const MONGO_URI =
  "mongodb+srv://studyforsixmonths:kshitij15pal@buzz.l1iomfs.mongodb.net/?retryWrites=true&w=majority&appName=buzz";

const creators = async () => {
  try {
    console.log("⏳ Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("✅ Connected to MongoDB");

    const influencers = [
      {
        userId: "6849107a89f366db77725ecf",
        handles: ["glam_with_vaishh"],
        followers: 2344,
        gender: "Female",
        location: "Hyderabad",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Short Curly Hair, PR Unboxing And Review, Makeup, Language-Telugu",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Vaishnavi-Hyderabad.mp4",
        avatar: "",
      },
      {
        userId: "6849107a89f366db77725ed2",
        handles: ["www.instagram.com/justsupersized"],
        followers: 4945,
        gender: "Male",
        location: "Pune",
        niche: ["Lifestyle/Fashion"],
        videoType: ["A Size Model, Clothing Reviews"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Akash%20Ranpise-Pune(15k).mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ed4",
        handles: [
          "https://www.instagram.com/devraj_ishtyles?igsh=aGV0bnN6c2ticzBn",
        ],
        followers: 3857,
        gender: "Male",
        location: "Bhagalpur",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Model, Styling Tips For Men"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Devraj%20I%20-%20Bihar(10k).mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ed6",
        handles: ["https://instagram.com/insanenaari?utm_medium=copy_link"],
        followers: 12300,
        gender: "Female",
        location: "Haryana",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Model, Black Curly Hairs"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Harshada%20Mohal-Haryana.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ed8",
        handles: [
          "https://www.instagram.com/ugcwith_ishita?igsh=MWFuOWxxNWZrM29qMA%3D%3D&utm_source=qr",
        ],
        followers: 1472,
        gender: "Female",
        location: "Kolkata",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Unboxing And PR Reviews, Makes Voice Over Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Ishita%20Prasad-Kolkata.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725eda",
        handles: ["jagrutiiii_15"],
        followers: 6370,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Straight Hairs, Funny- Relationship Reels"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Jagruti-Mumbai(5000).mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725edc",
        handles: ["kajallellwani"],
        followers: 3739,
        gender: "Female",
        location: "Pune",
        niche: ["Sports & Fitness"],
        videoType: ["Dance Creator, Small Business Owner, Yoga"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Kajal%20Lellwani-Pune(500).mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ede",
        handles: [
          "https://www.instagram.com/ugcwith_mithi?igsh=MTJ5YWhtOXpqcXQzbg%3D%3D&utm_source=qr",
        ],
        followers: 10100,
        gender: "Female",
        location: "Bihar",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Short Plum Color Hair, PR Unboxing And Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Mithi-Bihar.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ee0",
        handles: [
          "https://www.instagram.com/prranavvashistha?igsh=Z293dzczcXB6b3Rv",
        ],
        followers: 31600,
        gender: "Male",
        location: "Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Lifebalance, Emotional Wellbeing, Podcast"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Prranav%20Vashisitha-Delhi.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ee2",
        handles: ["https://www.instagram.com/sanikavasudeo/"],
        followers: 2248,
        gender: "Female",
        location: "Mumbai",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Long Curly Hair, Skincare And Haircare Review, Pet Adoption Reels",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Sanika%20Vasudeo-Mumbai.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ee4",
        handles: ["doggothepepper"],
        followers: 274,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Shih Tzu Breed Dog, Black And White Color"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Sara%20Gogna-Mumbai.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ee6",
        handles: [
          "https://www.instagram.com/shreya_goyal04?igsh=bzlteWlweWRyZ3N2",
        ],
        followers: 1240,
        gender: "Female",
        location: "Delhi",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["PR Unboxing, Singer, Straight Long Hairs"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Shreya%20Goyal-Delhi(3000).mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725ee8",
        handles: ["aamil.urrahman"],
        followers: 4785,
        gender: "Male",
        location: "",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Fun Voice Over Videos, PR Unboxing"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Aamil(10k).mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725eea",
        handles: ["aashigandhi_18"],
        followers: 675,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Gym, Sports, Dance Videos"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Aashi%20Gandhi-Mumbai.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725eec",
        handles: [
          "https://www.instagram.com/ugcwithaksha/profilecard/?igsh=MXJzd2hsOXlpY3BmdA==",
        ],
        followers: 2160,
        gender: "Female",
        location: "",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Unboxing, PR Reviews"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Aksha%20mansuri-Nodia.mp4",
        avatar: "",
      },
      {
        userId: "6849107b89f366db77725eee",
        handles: [
          "https://www.instagram.com/lifewithaksshhita?igsh=ODhpNzU4djZja2V0&utm_source=qr",
        ],
        followers: 2350,
        gender: "Female",
        location: "Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Short Black Hair, PR Unboxing And Skincare"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Akshita-Delhi(8k).mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725ef0",
        handles: [
          "https://www.instagram.com/_withlove_ann?igsh=NTVkNzgxaHI1MjRs&utm_source=qr",
        ],
        followers: 6586,
        gender: "Female",
        location: "",
        niche: ["Lifestyle/Fashion"],
        videoType: ["PR Unbox Videos, Guitar, Singer, Brown Eyes"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Anushree%20Shankar.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725ef2",
        handles: ["Bright_out_loud"],
        followers: 744,
        gender: "Female",
        location: "Gandhinagar",
        niche: ["Sports & Fitness"],
        videoType: [
          "Straight Long Black Hair, Nutrition, Gym, Homemade Nutritious Food Videos",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Arunima-Gandhinagar.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725ef4",
        handles: ["www.instagram.com/bhumi15__"],
        followers: 1251,
        gender: "Female",
        location: "Meerut",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Straight Black Hair With Red Highlights, Funny Videos, DIY",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Bhumi%20Bhardwaj-Meerut.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725ef6",
        handles: ["https://www.instagram.com/wherearethetuurtles/"],
        followers: 1844,
        gender: "Female",
        location: "Mumbai",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Black Curly Hairs, Bookworm, Writer"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Chandni%20Vadher-Mumbai.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725ef8",
        handles: [
          "https://www.instagram.com/_deepanshikatra___/profilecard/?igsh=MXp4dXlwOHM4NGxm",
        ],
        followers: 4353,
        gender: "Female",
        location: "Pune",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Cat Creator, PR Reviews, Unboxing Videos, Daily Vlogs"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Deepanshi%20katra-Pune.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725efa",
        handles: ["Ugcwithgia2"],
        followers: 3368,
        gender: "Female",
        location: "Indore",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Curly Short Hairs, Skincare Review, PR Unboxing"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Janhvi%20Hirani-Indore.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725efc",
        handles: [
          "https://www.instagram.com/khushi.uiux?igsh=MXM3eG1jMWozdWNzZg==",
        ],
        followers: 1933,
        gender: "Female",
        location: "Nagpur",
        niche: ["Informative: Education/Software/AI"],
        videoType: ["Ui/UX Teaching, Figma Pro, Educational"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Khushi%20Shroff-Nagpur.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725efe",
        handles: ["_mancce_"],
        followers: 5013,
        gender: "Female",
        location: "Mumbai",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Short Blue Dyed Hairs, PR Unboxing, Dance Creator"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Mansi%20Peshwani-Mumbai(8999).mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725f00",
        handles: [
          "https://www.instagram.com/meettbhanushali?igsh=eWlhbm9qZzh6aW1m",
        ],
        followers: 1177,
        gender: "Male",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Student Creator, Medium Long Hair"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Meet%20Bhanushali-Mumbai(3000).mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725f02",
        handles: ["https://www.instagram.com/neerajg917?igsh=cTl2dTd1Z2M0MXhy"],
        followers: 1094,
        gender: "Male",
        location: "Lucknow",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Gym Videos, Travel, Food, Couple"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Neeraj%20Jaiswal-Lucknow.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725f04",
        handles: [
          "https://www.instagram.com/girlwithwavy_hair?igsh=YXZwbGNueWc2cThp&utm_source=qr",
        ],
        followers: 1635,
        gender: "Female",
        location: "Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Short Curly Hair, PR Unboxing And Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Palak%20Babbar-Delhi(20000.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725f06",
        handles: ["@pihudoesntcare"],
        followers: 3681,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["PR Reviews, Long Brown Hairs, Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Pihu%20Malhotra-Mumbai.mp4",
        avatar: "",
      },
      {
        userId: "6849107c89f366db77725f08",
        handles: [
          "https://www.instagram.com/_pratiiikshaaaaa_?igsh=bGlkZDF5NnkxcmU2&utm_source=qr",
        ],
        followers: 22600,
        gender: "Female",
        location: "Pune",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Fashion, Unboxing, Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Pratiksha%20Shinde-Pune.mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f0a",
        handles: ["prekshha7"],
        followers: 1574,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Straight Golden Hairs, PR Unboxing And Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Preksha-Mumbai(3500).mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f0c",
        handles: ["@batmanjumps"],
        followers: 334,
        gender: "Male",
        location: "Kolkata",
        niche: ["Sports & Fitness"],
        videoType: [
          "Student Creator, Owns A Pet, Meme Account, Basketball Player",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Rahul-Kolkata(6-8k).mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f0e",
        handles: ["sakshihotchandanii"],
        followers: 1255,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Student Creator, Dance Creator, Black Curly Hair"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Sakshi%20Hotchandani-Mumbai(2000).mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f10",
        handles: ["sxmridhiarora"],
        followers: 18600,
        gender: "Female",
        location: "Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Student Creator, Owns A Pet, Knows Punjabi"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Samridhi%20arora-Delhi(3500).mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f12",
        handles: ["@subhav.kapoor"],
        followers: 6132,
        gender: "Male",
        location: "Noida",
        niche: ["Informative: Education/Software/AI"],
        videoType: [
          "No Beard, Curly Hair, Gym Content And Informative Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Subhav%20Kapoor-Noida(barter-2k).mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f14",
        handles: ["Vanshikashekhawatt"],
        followers: 20700,
        gender: "Female",
        location: "Chandigarh",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Golden Bob Hair, PR Unboxing, Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Vanshika-Chandigarh.mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f16",
        handles: [
          "https://www.instagram.com/vivienne_simte?igsh=MTR6emE0cTd5OHV3dA%3D%3D&utm_source=qr",
        ],
        followers: 2215,
        gender: "Female",
        location: "Haflong",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Straight Long Black Hair, PR Unboxing And Skincare"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Vivienne%20Simte-Assam(5500).mp4",
        avatar: "",
      },
      {
        userId: "6849107d89f366db77725f18",
        handles: ["vaishnavi_shingavi"],
        followers: 4103,
        gender: "Female",
        location: "Pune",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Student Creator, Short Brown Hair, Food And Outfit Videos",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/vaishnavi%20shingavi-Pune(1500).mp4",
        avatar: "",
      },
    ];

    console.log("📤 Inserting creators...");
    await Creator.insertMany(influencers);
    console.log("✅ Creators inserted successfully");
  } catch (err) {
    console.error("❌ Error inserting creators:", err);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from MongoDB");
  }
};

creators();
