import Creator from "./models/Creator.js";
import mongoose from "mongoose";
const MONGO_URI =
  "mongodb+srv://studyforsixmonths:kshitij15pal@buzz.l1iomfs.mongodb.net/?retryWrites=true&w=majority&appName=buzz";

const creators = async () => {
  try {
    console.log("⏳ Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("✅ Connected to MongoDB");

    const influencers = [
      {
        userId: "684455bd4c988ac26ce0551b",
        handles: [
          "https://www.instagram.com/arushigargg_/profilecard/?igsh=aGJtbzRwY2VhdzFo",
        ],
        followers: 9381,
        gender: "Female",
        location: "New Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["PR Unboxing And Reviews"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Black Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Aayushi%20Gupta-Delhi(400-500).mp4",
        avatar: "",
      },
      {
        userId: "684455bd4c988ac26ce0551e",
        handles: [
          "https://www.instagram.com/ok_aayushi_?igsh=N3c4dXp3MHVkZmht&utm_source=qr",
        ],
        followers: 1130,
        gender: "Female",
        location: "New Delhi",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Makeup", "Outfit Stylist", "PR Unboxing"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Brown Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Arushi%20Garg-Delhi(8000).mp4",
        avatar: "",
      },
      {
        userId: "684455bd4c988ac26ce05520",
        handles: ["Bhaavusjournal"],
        followers: 5115,
        gender: "Female",
        location: "Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Story Teller", "Informative Videos"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Brown Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Bhaavya%20gupta-Mumbai(4000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05522",
        handles: ["sheliiee.30"],
        followers: 3628,
        gender: "Female",
        location: "Jabalpur",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["PR Unboxing", "Skincare Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Dhelie-Jabalpur(500).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05524",
        handles: ["https://www.instagram.com/enuverse_/#"],
        followers: 1299,
        gender: "Female",
        location: "Jaipur",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Stylist", "Daily Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Short Brown Hair"],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Enu-Jaipur(300).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05526",
        handles: [
          "https://www.instagram.com/ishita.bhatt09?igsh=emh4ZW5qMnJ4dmQ5&utm_source=qr",
        ],
        followers: 3936,
        gender: "Female",
        location: "Dehradun / Delhi / Gurgaon / Bareilly",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Reviews"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Dance Creator"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Ishita%20Bhatt-Delhi(3-6k).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05528",
        handles: [
          "https://www.instagram.com/karabi_kashyap__here?igsh=MWxlY3lueG9lbnB0aw==",
        ],
        followers: 7276,
        gender: "Female",
        location: "For brand to send product",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Review", "Photoshoot", "Artist", "Dance Creator"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Assamese"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Karabi%20Kashyap-1000.mp4",
        avatar: "",
      },
      {
        userId: "68445611fdbd66ea5474b290",
        handles: [
          "https://www.instagram.com/_k_hu_s_h_i?igsh=cnp6emt3MW1rM212&utm_source=qr",
        ],
        followers: 1499,
        gender: "Female",
        location: "Mumbai and Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Stylist"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator"],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Khushi-Mumbai-Delhi.mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce0552c",
        handles: ["shouryeshahi"],
        followers: 4845,
        gender: "Male",
        location: "Delhi",
        niche: ["Food"],
        videoType: ["Food Content", "Cafe & Restaurant Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/shourye-Delhi(4000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce0552e",
        handles: [
          "https://www.instagram.com/shreyagaggar?igsh=MTQzdmN3MXU0YTZ3YQ%3D%3D&utm_source=qr",
        ],
        followers: 19100,
        gender: "Female",
        location: "Gurgaon",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit And Food Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Owns A Pet", "Couple Content"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Shreya%20Gaggar-Gurgoan(4500).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05530",
        handles: ["Snehgaur_"],
        followers: 3684,
        gender: "Female",
        location: "Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Spanish Learning", "Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Knows Spanish"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Sneh%20gaur-Delhi(5000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05532",
        handles: ["@swastikamitraa"],
        followers: 1372,
        gender: "Female",
        location: "Bangalore",
        niche: ["Lifestyle/Fashion"],
        videoType: [],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Swastika%20Mitra-Banglore(500).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05534",
        handles: ["Aishwaryasharma3"],
        followers: 3517,
        gender: "Female",
        location: "Mumbai",
        niche: ["Sports & Fitness"],
        videoType: ["Yoga And Nutrition Content", "Healthy Food"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Aishwarya%20Sharma-Mumbai(4000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05536",
        handles: ["Anwesha_Ayoshna"],
        followers: 10900,
        gender: "Female",
        location: "Bangalore",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Dance Creators", "Travel", "Food And Outfit Stylist"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Long Curly Hair", "Knows Odia"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Anwesha%20Ayoshna-Banglore(3000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce05538",
        handles: [
          "https://www.instagram.com/sundariiii_duniyaaaa/profilecard/?igsh=MXJhYXI5d3J4ZnhpbQ==",
        ],
        followers: 910,
        gender: "Female",
        location: "Lucknow",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["PR Unboxing", "Skincare Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Straight Long Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Archika-Lucknow(1000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce0553a",
        handles: [
          "https://www.instagram.com/atemiuu?igsh=MTc0eDMwZ3gyZG1tbg%3D%3D&utm_source=qr",
        ],
        followers: 2961,
        gender: "Female",
        location: "Nagaland",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["Skincare Review", "PR Unboxing"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Straight Short Black Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Atemla%20Shiu-Nagaland(2000).mp4",
        avatar: "",
      },
      {
        userId: "684455be4c988ac26ce0553c",
        handles: ["Ayushiiay"],
        followers: 6320,
        gender: "Female",
        location: "Nashik, Maharashtra",
        niche: ["Lifestyle/Fashion"],
        videoType: [
          "Outfit And Food Review",
          "Daily Insight Of Life",
          "Travel",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Ayushi%20jain-Nashik(3000).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce0553e",
        handles: [
          "https://www.instagram.com/glamsamples_bydisha?igsh=MWQzc2Rqc2VyY3g0bg==",
        ],
        followers: 32200,
        gender: "Female",
        location: "Mumbai",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["PR Unboxing", "Skincare And Perfume Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Black Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Disha%20Virmani-Mumbai(15k).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05540",
        handles: ["dr.rohu_25"],
        followers: 1246,
        gender: "Female",
        location: "Pune Dehu Road, Maharashtra",
        niche: ["Health & Wellness"],
        videoType: ["Book Review", "Transformation", "Life Insight"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Dentist", "Wavely Red Hair", "Knows Marathi"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Dr%20Rohini%20Jaybhaye-Pune(500).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05542",
        handles: [
          "https://www.instagram.com/drhimajareddypulyala?igsh=MXhyOTNmY2Y5c2Zraw==",
        ],
        followers: 6695,
        gender: "Female",
        location: "Hyderabad",
        niche: ["Health & Wellness"],
        videoType: [
          "Skin, Hair And Nail Expert",
          "Gym Content",
          "Treatment Plan",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Doctor"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Dr.%20Himaja%20Reddy-Hyderabad(15-20k).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05544",
        handles: ["Kirtimishty30"],
        followers: 2757,
        gender: "Female",
        location: "",
        niche: ["Sports & Fitness"],
        videoType: ["Fitness Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Owns A Pet", "Couple Content"],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Kirti%20Gosain.mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05546",
        handles: [
          "https://www.instagram.com/mahimagava?igsh=Z2FkbzB0bzB2bWVw&utm_source=qr",
        ],
        followers: 3473,
        gender: "Female",
        location: "Rudrapur, Uttarakhand",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Review", "Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Brown Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Mahima%20Gava-Uttrakhand.mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05548",
        handles: [
          "https://www.instagram.com/_malvikaaaaa_?igsh=MzViazhneDFoY2ow&utm_source=qr",
        ],
        followers: 3190,
        gender: "Female",
        location: "Noida",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Skincare Review", "Outfit Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Long Red Hair", "Doctor"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/malvika%20bhatt_noida(3000).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce0554a",
        handles: ["Ugc.with.mansi"],
        followers: 5107,
        gender: "Female",
        location: "Bangalore",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["PR Unboxing And Reviews"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Black Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Mansi-Banglore(4000).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce0554c",
        handles: ["Meemansaaaaaaa"],
        followers: 6058,
        gender: "Female",
        location: "Pune",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Short Brown Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Meemansa%20Tripathi-Pune(8000).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce0554e",
        handles: ["nehabaidd"],
        followers: 11400,
        gender: "Female",
        location: "Hyderabad",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Long Plum Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Neha%20Baid-Hyderabad(9k).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05550",
        handles: ["Ojasvi.kn"],
        followers: 1019,
        gender: "Female",
        location: "Delhi, Raipur, Bangalore",
        niche: ["Travel"],
        videoType: ["Food Content And Travel"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Brown Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Ojasvi%20Khandelwal-Delhi.mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05552",
        handles: [
          "https://www.instagram.com/thatprettyme_?igsh=MWl4b3lyOHJjZ2ZvNg%3D%3D&utm_source=qr",
        ],
        followers: 2896,
        gender: "Female",
        location: "Delhi",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Couple Content", "Outfit Stylist", "Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Priya-Delhi(3000).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05554",
        handles: [
          "https://www.instagram.com/priyankaavlogs_?igsh=MXNsN2Y0eHg0bXhldg==",
        ],
        followers: 3374,
        gender: "Female",
        location: "Bangalore",
        niche: ["Food"],
        videoType: ["Food Place Reviews"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [
          "Bride-To-Be",
          "Student Creator",
          "Owns A Pet",
          "Dance Creator",
          "Kannada",
        ],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Priyanka-Banglore(2000).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05556",
        handles: ["@raina.de8"],
        followers: 5063,
        gender: "Female",
        location: "Calcutta until July, London August onwards",
        niche: ["Informative: Education/Software/AI"],
        videoType: ["Travel Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Entrepreneur", "Long Curly Hair", "Knows Bengali"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Raina%20De-Kolkata(30k).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce05558",
        handles: ["chaoticexcerpts"],
        followers: 204,
        gender: "Female",
        location: "Delhi, Mumbai",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Stylist And Makeup"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Riya-Delhi-Mumbai(500).mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce0555a",
        handles: [
          "https://www.instagram.com/cariesassassin/profilecard/?igsh=dHNxcnB4eWNvMHJn",
        ],
        followers: 1901,
        gender: "Male",
        location: "Mumbai",
        niche: ["Health & Wellness"],
        videoType: ["Root Canal Specialist", "Dental Photographer"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Dentist"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Samarth%20Srivastava-Mumbai.mp4",
        avatar: "",
      },
      {
        userId: "684455bf4c988ac26ce0555c",
        handles: ["@nutrition_with_saumya"],
        followers: 591,
        gender: "Female",
        location: "Jaipur, Rajasthan",
        niche: ["Food"],
        videoType: [
          "Diet Nutrition Tips",
          "Lifestyle Disorders Like PCOD",
          "Obesity Weight Management",
          "Gym Progress",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Dietician"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Saumya%20Sarah%20Baristo-Jaipur(20k).mp4",
        avatar: "",
      },
      {
        userId: "684455c04c988ac26ce0555e",
        handles: ["Sindhooriiii"],
        followers: 1868,
        gender: "Female",
        location: "",
        niche: ["Home & Decor"],
        videoType: ["Home Decor And Cooking Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Knows Kannada"],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Sindhoori.mp4",
        avatar: "",
      },
      {
        userId: "684455c04c988ac26ce05560",
        handles: ["_smriteee_"],
        followers: 742,
        gender: "Female",
        location: "Kolkata",
        niche: ["Lifestyle/Fashion"],
        videoType: ["Outfit Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Short Brown Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Smriti%20Singh-Kolkata(3-5k).mp4",
        avatar: "",
      },
      {
        userId: "684455c04c988ac26ce05562",
        handles: [
          "https://www.instagram.com/supreetdhanjal01?igsh=OHV4ejRmemo2eW1q&utm_source=qr",
        ],
        followers: 3353,
        gender: "Female",
        location: "Bangalore",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: ["PR Unboxing", "Outfit Stylist", "Skincare Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Long Black Hair"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Supreet%20dhanjal-Banglore(1500).mp4",
        avatar: "",
      },
      {
        userId: "684455c04c988ac26ce05564",
        handles: ["Yaamini_shah"],
        followers: 6078,
        gender: "Female",
        location: "Mumbai",
        niche: ["Travel"],
        videoType: ["Travel And Food Content"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Yaamini%20Shah-Mumbai(8k).mp4",
        avatar: "",
      },
      {
        userId: "684455c04c988ac26ce05566",
        handles: ["eatwithyukti"],
        followers: 863,
        gender: "Female",
        location: "Gachibowli, Hyderabad",
        niche: ["Food"],
        videoType: ["Food Review", "Cafe And Restaurant Hopping"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Yukti-Hyderabad.mp4",
        avatar: "",
      },
      {
        userId: "684455c04c988ac26ce05568",
        handles: [
          "https://www.instagram.com/a_guywitha_camera?igsh=MWo2NW8xb3ZhNGxiNA%3D%3D&utm_source=qr",
        ],
        followers: 3068,
        gender: "Male",
        location: "Bhopal",
        niche: ["Lifestyle/Fashion"],
        videoType: [
          "Storyteller",
          "Film Maker",
          "Photographer",
          "Food Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: ["Student Creator", "Couple Content"],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Sandeep%20-Bhopal%20(1000).mp4",
        avatar: "",
      },
    ];

    console.log("📤 Inserting creators...");
    await Creator.insertMany(influencers);
    console.log("✅ Creators inserted successfully");
  } catch (err) {
    console.error("❌ Error inserting creators:", err);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from MongoDB");
  }
};

creators();
