import Creator from "./models/Creator.js";
import mongoose from "mongoose";
const MONGO_URI = "";

const creators = async () => {
  try {
    console.log("⏳ Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("✅ Connected to MongoDB");

    const influencers = [
      {
        userId: "684bbc49d4327ecee01b8619",
        handles: [
          "https://www.instagram.com/sri.s_all_that?igsh=anlhYmZiNTd5YXo4&utm_source=qr",
        ],
        followers: 18400,
        gender: "Female",
        location: "",
        niche: ["Informative: Education/Software/AI"],
        videoType: [
          "Storytelling Content",
          "Grwm Or Transitions",
          "Straight Black Hair",
          "Bengali Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Sriparna%20Tarafdar(1000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4ad4327ecee01b861c",
        handles: [
          "https://www.instagram.com/namish_sachdeva?igsh=MWppdmwxcGtieGc2&utm_source=qr",
        ],
        followers: 3284,
        gender: "Male",
        location: "",
        niche: ["Fashion"],
        videoType: [
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Outfit Review",
          "Long Hair",
          "Beard",
          "Gym Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Namish%20Sachdeva(3000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4bd4327ecee01b861e",
        handles: [
          "https://www.instagram.com/mohit.k_01?igsh=OHprd2Fodjk1eWcx&utm_source=qr",
        ],
        followers: 5015,
        gender: "Male",
        location: "Mumbai",
        niche: ["Sports & Fitness"],
        videoType: [
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Gym Content",
          "Outfit Review",
          "Voiceover",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Mohit%20khubani-Mumbai-Fitness(4500).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4bd4327ecee01b8620",
        handles: [
          "https://www.instagram.com/_thefashionmaven_?igsh=bjF6bWk1dGJwZGQ4&utm_source=qr",
        ],
        followers: 5421,
        gender: "Male",
        location: "",
        niche: ["Fashion"],
        videoType: ["Grwm Or Transitions", "Outfit Review"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Aryan%20Sharma(2000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4bd4327ecee01b8622",
        handles: [
          "https://www.instagram.com/visheshkatariaa?igsh=czN4bXV0Z2NjcTVk&utm_source=qr",
        ],
        followers: 1147,
        gender: "Male",
        location: "Delhi",
        niche: ["Fashion"],
        videoType: [
          "Grwm Or Transitions",
          "Outfit Review",
          "Beard",
          "Couple Videos",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Vishesh%20Kataria-Delhi(1000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4bd4327ecee01b8624",
        handles: [
          "https://instagram.com/piyush_bhidola?igshid=NzZlODBkYWE4Ng==",
        ],
        followers: 8058,
        gender: "Male",
        location: "Mumbai",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Styling Tips",
          "Skincare",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Piyush%20Bhidola-Mumbai(3.5k-8k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4bd4327ecee01b8626",
        handles: [
          "https://www.instagram.com/dr.yashgupta_?igsh=MXUya3d2eHY3cnZndw%3D%3D&utm_source=qr",
        ],
        followers: 9834,
        gender: "Male",
        location: "Kanpur",
        niche: ["Sports & Fitness"],
        videoType: [
          "Student Creator",
          "Dance Creator",
          "Business Content",
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Doctor",
          "Fitness",
          "Gym Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Dr.Yash%20gupta-Kanpur-Fitness(5k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b8628",
        handles: ["Riishiii.14"],
        followers: 1954,
        gender: "Male",
        location: "",
        niche: ["Fashion"],
        videoType: [
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Long Hair",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Rishi%20Khandelwal(7k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b862a",
        handles: [
          "https://www.instagram.com/harshal_bright_world?igsh=OW90NHVleTJmZDho&utm_source=qr",
        ],
        followers: 2334,
        gender: "Male",
        location: "Mumbai",
        niche: ["Fashion"],
        videoType: [
          "Business Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Outfit Review",
          "Fitness",
          "Gym Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Harshal%20Chavan-Mumbai(10k-15k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b862c",
        handles: ["d_danish_sharma"],
        followers: 2720,
        gender: "Male",
        location: "",
        niche: ["Fashion"],
        videoType: [
          "Grwm Or Transitions",
          "Outfit Review",
          "Spooky Content",
          "Vintage",
          "Fitness",
          "Gym Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Danish%20sharma(3k-5k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b862e",
        handles: ["https://www.instagram.com/thisisnazil"],
        followers: 12200,
        gender: "Male",
        location: "Indore",
        niche: ["Fashion"],
        videoType: [
          "Grwm Or Transitions",
          "Travel Content",
          "Food Review",
          "Resturant&Cafe Hopping",
          "Gym Content",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Nazil%20Khan-Indore-Food(2k-4k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b8630",
        handles: ["Instagram.com/the_bhavay_jain"],
        followers: 1131,
        gender: "Male",
        location: "",
        niche: ["Fashion"],
        videoType: [
          "Business Content",
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "UGC Content",
          "Fitness",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Bhavay%20Jain.mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b8632",
        handles: ["@nishantttttttt"],
        followers: 16400,
        gender: "Male",
        location: "Pune/Mumbai",
        niche: ["Fashion"],
        videoType: [
          "Grwm Or Transitions",
          "Outfit Review",
          "Skincare",
          "Perfumes",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Nishant-Pune(16k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4cd4327ecee01b8634",
        handles: ["https://www.instagram.com/prifit_6?igsh=NXN6dWN1MjY3Njd3"],
        followers: 9840,
        gender: "Female",
        location: "",
        niche: ["Sports & Fitness"],
        videoType: [
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Gym",
          "Yoga",
          "PCOD",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Priyanka%20Dhingra(3k).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4dd4327ecee01b8636",
        handles: ["https://www.instagram.com/yebaniyaladki"],
        followers: 2049,
        gender: "Female",
        location: "",
        niche: ["Food"],
        videoType: ["Business Content", "Lifestyle", "Food", "Memes"],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Jyoti%20Mittal(1000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4dd4327ecee01b8638",
        handles: ["https://www.instagram.com/srishti_s_bhatia"],
        followers: 7934,
        gender: "Female",
        location: "",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Skincare",
          "PR Reviews",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Srishti%20Sachdeva%20Bhatia(1000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4dd4327ecee01b863a",
        handles: ["https://instagram.com/kannaakk?igshid=YmMyMTA2M2Y="],
        followers: 2704,
        gender: "Female",
        location: "",
        niche: ["Fashion"],
        videoType: [
          "Student Creator",
          "Grwm Or Transitions",
          "Outfit Review",
          "Skincare",
          "Curly Hair",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Kanak%20Goyal(2000).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4dd4327ecee01b863c",
        handles: ["_iamprernaprasad"],
        followers: 2232,
        gender: "Female",
        location: "Kolkata",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Bride-to-be",
          "Student Creator",
          "Storytelling Content",
          "Unboxing Videos",
          "Grwm Or Transitions",
          "Skincare",
          "Makeup",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos: "https://d242xts6unflx7.cloudfront.net/Prerna-Kolkata(700).mp4",
        avatar: "",
      },
      {
        userId: "684bbc4dd4327ecee01b863e",
        handles: [
          "https://www.instagram.com/nannu_bittu_?igsh=MXMxc244aHRndGZrNg%3D%3D&utm_source=qr",
        ],
        followers: 1626,
        gender: "Female",
        location: "",
        niche: ["Beauty: Skincare/Haircare/Makeup"],
        videoType: [
          "Mom Creator (Parent)",
          "Couple Content",
          "Lifestyle",
          "Skincare",
        ],
        agegroup: "",
        platform: "Instagram",
        price: null,
        creatortags: [""],
        admintags: [""],
        videos:
          "https://d242xts6unflx7.cloudfront.net/Prakrati%20sharma(1000).mp4",
        avatar: "",
      },
    ];

    console.log("📤 Inserting creators...");
    await Creator.insertMany(influencers);
    console.log("✅ Creators inserted successfully");
  } catch (err) {
    console.error("❌ Error inserting creators:", err);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from MongoDB");
  }
};

creators();
